import { theme } from "./theme.js";

export const tokens = {
  colors: {
    primary: theme.colors.primary,
    primaryHover: theme.colors.primaryHover,
    backgroundDark: theme.colors.background,
    surfaceDark: theme.colors.surface,
    surfaceDarkElevated: theme.colors.surfaceSecondary,
    borderDark: theme.colors.border,
    textPrimary: theme.colors.textPrimary,
    textMuted: theme.colors.textSecondary,
    textSoft: "#CBD5E1",
    backgroundLight: theme.colors.adminBackground,
    surfaceLight: theme.colors.adminSurface,
    borderLight: theme.colors.adminBorder,
    adminInk: theme.colors.adminText,
    adminMuted: theme.colors.adminTextSecondary,
    success: theme.colors.success,
    warning: theme.colors.warning,
    danger: theme.colors.danger,
  },
  spacing: {
    none: "0",
    xs: theme.spacing[8],
    sm: theme.spacing[8],
    md: theme.spacing[12],
    lg: theme.spacing[16],
    xl: theme.spacing[20],
    "2xl": theme.spacing[24],
    "3xl": theme.spacing[32],
    "4xl": theme.spacing[40],
    "5xl": theme.spacing[48],
    "6xl": theme.spacing[64],
    8: theme.spacing[8],
    12: theme.spacing[12],
    16: theme.spacing[16],
    20: theme.spacing[20],
    24: theme.spacing[24],
    32: theme.spacing[32],
    40: theme.spacing[40],
    48: theme.spacing[48],
    64: theme.spacing[64],
    pageX: "1rem",
    pageXDesktop: "2rem",
    sectionGap: "2.5rem",
  },
  radius: {
    sm: theme.radius.sm,
    md: theme.radius.md,
    lg: theme.radius.lg,
    xl: theme.radius.xl,
    full: theme.radius.full,
  },
  shadows: {
    adminCard: theme.shadows.adminCard,
    storeCard: theme.shadows.cardDark,
    storeCardHover: theme.shadows.cardDarkHover,
    neonBlue: theme.shadows.blueGlow,
    neonBlueStrong: theme.shadows.blueGlowStrong,
    innerHighlight: theme.shadows.innerHighlight,
  },
  typography: {
    scale: theme.typography,
    fontFamily: {
      sans: ["Inter", "system-ui", "sans-serif"],
    },
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "3.75rem",
    },
    fontWeight: {
      medium: "500",
      semibold: "600",
      bold: "700",
      black: "900",
    },
    lineHeight: {
      tight: "1.15",
      normal: "1.5",
      relaxed: "1.7",
    },
  },
  zIndex: {
    base: "0",
    raised: "10",
    dropdown: "20",
    sticky: "40",
    modal: "50",
    toast: "60",
  },
  transitions: {
    duration: {
      fast: "160ms",
      base: "220ms",
      premium: "280ms",
      slow: "420ms",
    },
    easing: {
      standard: "ease",
      premium: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
  },
};

export default tokens;
